vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: '/img/productos'
            upload_destination: '%kernel.project_dir%/public/img/productos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            # para eliminar los ficheros
            delete_on_update: true
            delete_on_remove: true
